name: Build Orco EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Recuperation du code
      uses: actions/checkout@v4 # Passage en v4

    - name: Installation de Python
      uses: actions/setup-python@v5 # Passage en v5
      with:
        python-version: '3.10'

    - name: Installation des dependances
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller psutil watchdog colorama

    - name: Compilation en EXE
      run: |
        pyinstaller --onefile --noconsole --uac-admin --name "Orco_Titan_Ultra" antivirus.py

    - name: Sauvegarde de l EXE
      uses: actions/upload-artifact@v4 # Passage en v4 (C'est ICI que Ã§a bloquait)
      with:
        name: Mon_Antivirus_EXE
        path: dist/Orco_Titan_Ultra.exe
        
