name: Build Orco EXE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Recuperation du code
      uses: actions/checkout@v3

    - name: Installation de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installation des dependances
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller psutil watchdog colorama

    - name: Compilation en EXE
      # J'ai changé le nom ici pour correspondre à ton fichier antivirus.py
      run: |
        pyinstaller --onefile --noconsole --uac-admin --name "Orco_Titan_Ultra" antivirus.py

    - name: Sauvegarde de l EXE
      uses: actions/upload-artifact@v3
      with:
        name: Mon_Antivirus_EXE
        path: dist/Orco_Titan_Ultra.exe

